---
title: "Registration"
---
Join us for Synbio 6.0 by securing your spot today. The registration fee of **210 CAD** provides you with full access to the conference sessions, materials, networking and meals.

<div class="center-text">
<p style="margin-top: 20px; font-size: 30px;">
    Register now at 
    <a href="https://ubc.ungerboeck.net/prod/emc00/register.aspx?aat=4f574970714f535370316839566d35425736627675624766354b7737395a4364592b443268586d796e396b3d" style="color: #133E67; font-weight: bold;">
        this link
    </a>
</p>
</div>

::: center-text
<h3>Important Dates</h3>

|                                  |             Date             |
|----------------------------------|:----------------------------:|
| **Registration Opens**           |    **February 12th 2024**    |
| **Registration Ends**            |       **May 9th 2024**       |
| **Abstract Submission Deadline** |     **April 17th 2024**      |
| **Conference**                   | **May 16th - May 17th 2024** |
:::


## Abstract Submission:

<div class="center-text" style="font-size: 30px;">

Abstracts can be submitted  <a href="https://forms.gle/ZpVNQsiWAWdBJN4f9" style="color: #133E67; font-weight: bold; "> here </a>
</div>

All attendees are encouraged to submit abstracts. You can see the submission deadlines along with other important dates above. Abstracts are limited to \~2900 characters. Attendees will be notified regarding their abstract status a week after the submission deadline. Selected presenters will also be notified if they have been chosen to give a 15 minutes oral presentation in addition to poster presentation. **Abstract submission deadline is April 17th 2024**. Please make sure to register before submitting the abstract


## Accomodation:

Exclusive accommodation options are available on the UBC Campus for conference attendees. These selected accommodations ensure a comfortable and convenient stay. For booking and payment, attendees can access the reservation through this **[link](https://reserve.suitesatubc.com/vancouver/availability.asp?hotelCode=%2A&startDate=05%2F15%2F2024&endDate=05%2F18%2F2024&adults=1&children=&rooms=1&requesttype=invBlockCode&code=G240515B%20)**. **Deadline to reserve rooms at the subsidized rate is April 17th!**

## Cancellation Policy

Attendees can get a full refund if they cancel over 60 days before the conference. Cancellations made between 30 to 60 days prior are eligible for a 50% refund. No refunds are provided for cancellations within 30 days of the event. All cancellation refunds incur a 35 CAD administrative charge. 